<?php
session_start();
error_reporting(0);
require('conf.php');
require('funciones.php');
include('permisos.php');
if (is_ajax())
{
    $conse = $_POST['conse'];
    $batallon = $_POST['batallon'];
    $pregunta = "SELECT * FROM cx_pla_tra WHERE conse='$conse' AND unidad='$batallon'";
    $sql = odbc_exec($conexion,$pregunta);
    $conse = odbc_result($sql,1);
    $batallon = odbc_result($sql,4);
    $compania = trim(utf8_encode(odbc_result($sql,5)));
    $placa = odbc_result($sql,6);
    $aseguradora = trim(utf8_encode(odbc_result($sql,7)));
    $fecha = substr(odbc_result($sql,8),0,10);
    $riesgo = odbc_result($sql,9);
    $aseguradora1 = trim(utf8_encode(odbc_result($sql,10)));
    $soat = trim(odbc_result($sql,11));
    $fecha1 = substr(odbc_result($sql,12),0,10);
    $fecha2 = substr(odbc_result($sql,13),0,10);
    $fecha3 = substr(odbc_result($sql,14),0,10);
    $mantenimiento = trim(utf8_encode(odbc_result($sql,15)));
    $mantenimiento1 = trim(utf8_encode(odbc_result($sql,16)));
    $clase = odbc_result($sql,17);
    $marca = trim(utf8_encode(odbc_result($sql,18)));
    $linea = trim(utf8_encode(odbc_result($sql,19)));
    $modelo = trim(utf8_encode(odbc_result($sql,20)));
    $cilindraje = trim(utf8_encode(odbc_result($sql,21)));
    $activo = trim(utf8_encode(odbc_result($sql,22)));
    $costo = trim(utf8_encode(odbc_result($sql,23)));
    $tipo = odbc_result($sql,24);
    $color = trim(utf8_encode(odbc_result($sql,25)));
    $motor = trim(utf8_encode(odbc_result($sql,26)));
    $chasis = trim(utf8_encode(odbc_result($sql,27)));
    $matricula = trim(utf8_encode(odbc_result($sql,28)));
    $estado = odbc_result($sql,29);
    $fecha4 = substr(odbc_result($sql,30),0,10);
    $origen = trim(utf8_encode(odbc_result($sql,31)));
    $equipo = trim(utf8_encode(odbc_result($sql,32)));
    $consumo = trim(utf8_encode(odbc_result($sql,33)));
    $kilometro = trim(utf8_encode(odbc_result($sql,34)));
    $observaciones = trim(utf8_encode(odbc_result($sql,35)));
    $empadrona = odbc_result($sql,38);
    $odometro = odbc_result($sql,39);
    $autoriza = odbc_result($sql,40);
    $inventa = trim(odbc_result($sql,41));
    $fecha7 = substr(odbc_result($sql,42),0,10);
    $fecha8 = substr(odbc_result($sql,43),0,10);
    $salida = new stdClass();
    $salida->conse = $conse;
    $salida->batallon = $batallon;
    $salida->compania = $compania;
    $salida->placa = $placa;
    $salida->aseguradora = $aseguradora;
    $salida->fecha = $fecha;
    $salida->riesgo = $riesgo;
    $salida->aseguradora1 = $aseguradora1;
    $salida->soat = $soat;
    $salida->fecha1 = $fecha1;
    $salida->fecha2 = $fecha2;
    $salida->fecha3 = $fecha3;
    $salida->mantenimiento = $mantenimiento;
    $salida->mantenimiento1 = $mantenimiento1;
    $salida->clase = $clase;
    $salida->marca = $marca;
    $salida->linea = $linea;
    $salida->modelo = $modelo;
    $salida->cilindraje = $cilindraje;
    $salida->activo = $activo;
    $salida->costo = $costo;
    $salida->tipo = $tipo;
    $salida->color = $color;
    $salida->motor = $motor;
    $salida->chasis = $chasis;
    $salida->matricula = $matricula;
    $salida->estado = $estado;
    $salida->fecha4 = $fecha4;
    $salida->origen = $origen;
    $salida->equipo = $equipo;
    $salida->consumo = $consumo;
    $salida->kilometro = $kilometro;
    $salida->observaciones = $observaciones;
    $salida->empadrona = $empadrona;
    $salida->odometro = $odometro;
    $salida->autoriza = $autoriza;
    $salida->inventa = $inventa;
    $salida->fecha7 = $fecha7;
    $salida->fecha8 = $fecha8;
    echo json_encode($salida);
}
?>