<?php
session_start();
error_reporting(0);
require('conf.php');
require('funciones.php');
include('permisos.php');
if (is_ajax())
{
  $tipo = $_POST['tipo'];
  $conse = $_POST['conse'];
  $ano = $_POST['ano'];
  $pregunta = "SELECT * FROM cx_reg_rec WHERE conse='$conse' AND ano='$ano' AND estado IN ('','Y') AND tipo='$tipo'";
  $sql = odbc_exec($conexion,$pregunta);
  $total = odbc_num_rows($sql);
  $salida = new stdClass();
  $i = 1;
  while($i<$row=odbc_fetch_array($sql))
  {
    $conse = odbc_result($sql,1);
    $fecha = substr(odbc_result($sql,2),0,10);
    $estado = odbc_result($sql,6);
    $ano = odbc_result($sql,7);
    $fec_res = trim(odbc_result($sql,8));
    $hr = trim(odbc_result($sql,9));
    $fec_hr = trim(odbc_result($sql,10));
    $dias = odbc_result($sql,11);
    $oficio = trim(odbc_result($sql,12));
    $fec_ofi = trim(odbc_result($sql,13));
    $prorroga = trim(odbc_result($sql,14));
    $fec_pro = trim(odbc_result($sql,15));
    $unidad = odbc_result($sql,16);
    $unidad1 = odbc_result($sql,17);
    $brigada = odbc_result($sql,18);
    $division = odbc_result($sql,19);
    $sintesis = trim($row["sintesis"]);
    $sintesis = utf8_encode($sintesis);
    $valor = trim(odbc_result($sql,21));
    $valor1 = odbc_result($sql,22);
    $fec_sum = trim(odbc_result($sql,23));
    $n_ordop = trim(utf8_encode(odbc_result($sql,24)));
    $ordop = trim(utf8_encode(odbc_result($sql,25)));
    $fec_ord = trim(odbc_result($sql,26));
    $fragmentaria = trim(utf8_encode(odbc_result($sql,27)));
    $fec_fra = trim(odbc_result($sql,28));
    $sitio = trim(utf8_encode(odbc_result($sql,29)));
    $municipio = odbc_result($sql,30);
    $departamento = odbc_result($sql,31);
    $factor = odbc_result($sql,32);
    $estructura = odbc_result($sql,33);
    $resultado = trim($row["resultado"]);
    $resultado = utf8_encode($resultado);
    $cedulas = trim($row["cedulas"]);
    $cedulas = utf8_encode($cedulas);
    $nombres = trim($row["nombres"]);
    $nombres = utf8_encode($nombres);
    $porcentajes = trim($row["porcentajes"]);
    $porcentajes = utf8_encode($porcentajes);
    $porcentajes1 = trim($row["porcentajes1"]);
    $porcentajes1 = utf8_encode($porcentajes1);
    $actas = trim($row["actas"]);
    $actas = utf8_encode($actas);
    $fechas = trim($row["fechas"]);
    $fechas = utf8_encode($fechas);
    $valores = trim($row["valores"]);
    $valores = utf8_encode($valores);
    $valores1 = trim($row["valores1"]);
    $valores1 = utf8_encode($valores1);
    $observaciones = trim($row["observaciones"]);
    $observaciones = utf8_encode($observaciones);
    $directiva = odbc_result($sql,44);
    $codigo = trim(odbc_result($sql,45));
    $tipo1 = odbc_result($sql,46);
    $lista = trim($row["lista"]);
    $tipo = odbc_result($sql,54);
    $oms = trim(odbc_result($sql,55));
    $recoleccion = odbc_result($sql,56);
    $num_reco = trim(odbc_result($sql,57));
    $fec_reco = trim(odbc_result($sql,58));
    $difusion = odbc_result($sql,59);
    $num_difu = trim(odbc_result($sql,60));
    $fec_difu = trim(odbc_result($sql,61));
    $condujo = odbc_result($sql,62);
    $radiograma = trim(odbc_result($sql,63));
    $fec_radi = trim(odbc_result($sql,64));
    $i++;
  }
  $salida->conse = $conse;
  $salida->fecha = $fecha;
  $salida->estado = $estado;
  $salida->ano = $ano;
  $salida->fec_res = $fec_res;
  $salida->hr = $hr;
  $salida->fec_hr = $fec_hr;
  $salida->dias = $dias;
  $salida->oficio = $oficio;
  $salida->fec_ofi = $fec_ofi;
  $salida->prorroga = $prorroga;
  $salida->fec_pro = $fec_pro;
  $salida->unidad = $unidad;
  $salida->unidad1 = $unidad1;
  $salida->brigada = $brigada;
  $salida->division = $division;
  $salida->sintesis = $sintesis;
  $salida->valor = $valor;
  $salida->valor1 = $valor1;
  $salida->fec_sum = $fec_sum;
  $salida->n_ordop = $n_ordop;
  $salida->ordop = $ordop;
  $salida->fec_ord = $fec_ord;
  $salida->fragmentaria = $fragmentaria;
  $salida->fec_fra = $fec_fra;
  $salida->sitio = $sitio;
  $salida->municipio = $municipio;
  $salida->departamento = $departamento;
  $salida->factor = $factor;
  $salida->estructura = $estructura;
  $salida->resultado = $resultado;
  $salida->cedulas = $cedulas;
  $salida->nombres = $nombres;
  $salida->porcentajes = $porcentajes;
  $salida->porcentajes1 = $porcentajes1;
  $salida->actas = $actas;
  $salida->fechas = $fechas;
  $salida->valores = $valores;
  $salida->valores1 = $valores1;
  $salida->observaciones = $observaciones;
  $salida->directiva = $directiva;
  $salida->codigo = $codigo;
  $salida->tipo1 = $tipo1;
  $salida->lista = $lista;
  $salida->tipo = $tipo;
  $salida->oms = $oms;
  $salida->recoleccion = $recoleccion;
  $salida->num_reco = $num_reco;
  $salida->fec_reco = $fec_reco;
  $salida->difusion = $difusion;
  $salida->num_difu = $num_difu;
  $salida->fec_difu = $fec_difu;
  $salida->condujo = $condujo;
  $salida->radiograma = $radiograma;
  $salida->fec_radi = $fec_radi;
  echo json_encode($salida);
}
?>